version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: direcional_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_strong_password123' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: ./src/Direcional.Api
      dockerfile: Dockerfile
    container_name: direcional_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Connection string para a API (dentro da rede do compose o host é "sqlserver")
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=Direcional;User Id=sa;Password=Your_strong_password123;Encrypt=True;TrustServerCertificate=True
      # (Opcional) JWT – ajuste conforme seu Program.cs/appsettings
      - Jwt__Issuer=Direcional
      - Jwt__Audience=DirecionalUsers
      - Jwt__Key=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mssqldata:
